services:
  - type: web
    name: onu-parts-tracker
    env: node
    region: oregon
    buildCommand: npm install && npm run build
    startCommand: node dist/index.js
    envVars:
      - key: NODE_ENV
        value: production
